#+title: Landslide Scaling Across The Solar System
#+date: April 21 2024
#+options: toc:nil
#+bibliography: landslide_scaling.bib
#+cite_export: natbib

* Scientific Motivation
Landslides are fundamental surface processes that play an important role in sediment transport and landscape evolution in terrestrial environments.
With the advent of high-resolution imagery we have observed landslides on many other (non-Earth) bodies, including the Moon, Mars, Venus, Mercury, and various asteroids.

The differences between these bodies gives us a way to study the impact of gravity, the atmosphere, subsurface fluids, and the geologic environment on landslide properties.
* Existing Landslide Catalogs
** Mercury
Researchers have mapped landslides on crater slopes on Mercury [cite:@brunetti_large_2015].
They used imagery from the Mercury Dual Imaging System (MDIS; 250 m/pixel).
A DEM was not available for Mercury when they conducted their study.
They compiled a catalog of 58 landslides in 38 craters.
** Earth
There is an abundance of mapped landslide catalogs on Earth.
I will not analyze all existing catalogs but will instead include several that represent diverse climatic, hydrologic, and geologic settings.
*** Washington State
The Washington State Geologic Survey has mapped landslides throughout the state to better understand the risks they pose to people and infrastructure [cite:@washington_geological_washington_2017].
To identify and map landslides they use orthoimagery and DEMs generated from high-quality lidar data (max of 2 m/pixel) collected by aerial surveys.
This represents the current highest resolution approach to mapping landslides.
** The Moon
Researchers have mapped landslides on crater slopes on the Moon [cite:@brunetti_large_2015].
Their study only considered landslides over 10^6 m^2.
To identify and map landslides, they used imagery from the Wide Angle Camera on the Lunar Reconnaissance Orbiter Camera (100 m/pixel), as well as a global DEM (100 m grid size).
They found 60 landslides in 35 craters.
** Mars
Researchers have undertaken a project to systematically map landslides on Mars [cite:@crosta_introducing_2018].
They analyzed the planet over latitudes from \minus60° to \plus60° and only mapped landslides greater than 10^5 m^2.
To globally identify landslides they used imagery from the High Resolution Stereo Camera on Mars Express (18 m/pixel), the Mars Orbital Camera (1.5--12 m/pixel), and the Context Imager (5--6 m/pixel) as well as 400 m gridded topography from the Mars Orbital Laser Altimeter (MOLA).
To locally map landslides they used HiRISE imagery (0.3 m/pixel) and DEMs from HRSC (50--150 m grid size) and MOLA (463 m grid size) when the HRSC-derived DEM was not available.
Their final catalog contains 3,000+ landslides.
* Scaling Analyses
** Landslide Frequency vs. Area
A common technique when analyzing landslide catalogs is to examine the relationship between landslide frequency and area [cite:@malamud_landslide_2004].

Let $A$ be the landslide area. Then a probability density function $p(A)$ is defined such that that probability of a landslide occurring within a range of areas $A_{\mathrm{min}}$ to $A_{\mathrm{max}}$ is given by
$$ Pr[A_{\mathrm{min}} \le A \le A_{\mathrm{max}}] = \int_{A_{\mathrm{min}}}^{A_{\mathrm{max}}}p(A)dA. $$
This probability density function can estimated from the finite samples in a landslide catalog using kernel density estimation.
I used the implementation in =scikit-learn= with a Gaussian kernel and Scott's method for estimating the bandwidth.
Due to the wide range of landslide areas, I performed the kernel density estimation in log space.

Figure [[fig:prob_area]] shows the frequency-area relationship for all included landslide catalogs.

#+caption: TODO
#+name: fig:prob_area
[[file:prob_area.pdf]]

* Discussion

* Conclusions

* References
#+print_bibliography:
